Rewrite of german Credit Part 1
mlr-org/mlr3gallery pull request #18
Opened 2020-03-23 16:48 UTC by pkopper

Basically I added a few things but mostly I improved the readability to "real text"
The last section, however, is entirely new.

2020-03-26 18:40 UTC, pat-s approved these changes

2020-03-26 18:42 UTC, pat-s requested changes
Thanks! Please fix the CI build.

2020-03-26 18:42 UTC, pat-s commented on content/post/mlr3_basics_german_credit.Rmd
> +As the `"GermanCredit"` data set is frequently used within `r mlr_pkg("mlr3")`, there is a task already existing just for this purpose.
`mlr_pkg()` only works in the mlr3book.

2020-03-27 14:54 UTC, pfistfl commented on content/post/mlr3_basics_german_credit.Rmd
> -- We have a look at the data set before we start modeling.
Why remove this?

2020-04-19 17:29 UTC, closed without merging

2020-04-22 14:32 UTC, pat-s commented
@pkopper Please add a short notice why you close a PR like this suddenly.